config/routes.rb
Rails.application.routes.draw do
  get 'document_comments/create'
  resources :procesos
  resources :documents
  resources :document_types
  resources :created_fields
  resources :fields
  resources :process_maps
  resources :proces
  resources :positions
  resources :diagnosticos

  post "document_comment", to: "document_comments#create",  as: "document_comment"
  get "comment_index", to: "document_comments#comment_index", as: "comment_index"

  root 'home#index'
  get "user/new", to: "home#user", as: "user"
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  post '/tinymce_assets', to: 'tinymce_assets#create'

  devise_scope :user do
    post "create_user", to: "users/registrations#create_user", as: "create_user" 
  end
  get "all_users", to: "home#create_user", as: "users"
  
  patch "document_update/:id/:number", to: "documents#update_docu", as: "document_update"
  
  post "version_document/:id", to: "documents#new_document", as: "nuevo_document"

  post "documents_ready/:id", to: "documents#ready", as: "documents_ready"
  get "pdf_docment/:id", to: "documents#documents_pdf", as: "pdf_document"
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
    @review = Document.where(user_review_id: current_user.id).where(state_review: false, finish_document: true)
    @aprove = Document.where(user_aprove_id: current_user.id).where(state_aprove: false, finish_document: true, state_review: true)
  end

  def create_user
  	@user = User.all
  end

  def user

  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/create_user.html.erb
<div class="orders">
  <div class="row">
    <div class="col-xl-12">
      <div class="card">

        <div class="card-body">
          <h4 class="box-title">Usuarios Registrados </h4>
        </div>

        <div class="card-body">
          <div class="table-stats order-table ov-h">
            <table class="table table_form ">

              <thead>
                <tr>
                  <th class="serial">#</th>
                  <th class="avatar">Avatar </th>
                  <th>Nombre</th>
                  <th>Apellido</th>
                  <th>Segundo Apellido</th>
                  <th>Tipo de Documento</th>
                  <th>Numero de Documento</th>
                  <th colspan="3">Email</th>
                </tr>
              </thead>

              <tbody>
                <% @user.each_with_index do |user, position| %>
                  <tr id="dele<%= user.id%>">
                    <td class="serial"><%= position + 1 %>.</td>
                    <td class="avatar">
                    	<div class="round-img">
                    		<%= user.avatar? ? image_tag(user.avatar_url(), class: "rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "rounded-circle")%>
                        </div>
                    </td>
                    <td><%= user.first_name if user.first_name %></td>
                    <td><%= user.first_last_name if user.first_last_name %></td>
                    <td><%= user.second_last_name if user.second_last_name %></td>
                    <td><%= user.document_type if user.document_type %></td>
                    <td><%= user.document_number if user.document_number %></td>
                    <td><%= user.email %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div> 
        </div>

        <div class="col-md-12 modal-footer">
          <%= link_to 'Crear Usuario', user_path, class: "btn btn-success " %>
        </div>

      </div> 
    </div>  
  </div>
</div>

app/views/home/index.html.erb
<div class="col-xl-12">
   <div class="card">
      <div class="card-body">
      <h4> Bienvenido <%= current_user.first_name? ? current_user.first_name : "Usuario de BeeTools"  %></h4>
      	<br>
      	<div class="row">
      		<% if @review.any? %>
	      		<div class="col-xl-6">
	      			<div class="table-stats order-table ov-h">
			            <table class="table table_form ">

			              <thead>
			            		<tr>
			            			<th colspan="3"><span class="badge badge-warning"> Tienes <%= @review.count %> Documento Pendiente Revisar</span></th>
			            		</tr>
			              </thead>
			              <thead>
			                <tr>
			                  <th class="serial">#</th>
			                  <th>Usuario</th>
			                  <th>Informacion</th>
			                </tr>
			              </thead>

			              <tbody>
			                <% @review.each_with_index do |review, position| %>
			                  <tr>
			                    <td class="serial"><%= position + 1 %>.</td>
			                    <td class="avatar">
			                      <div class="round-img">
			                        <%= review.user.avatar? ? image_tag(review.user.avatar_url(), class: "rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "rounded-circle")%>
			                        </div>
			                    </td>
			                     <td>
			                    	<div class="text-center">
			                    		<a href="/documents/<%= review.id %>">
			         						<i class="fas fa-info-circle"></i>
			         					</a>
			                    	</div>
			                    </td>
			                  </tr>
			                <% end %>
			              </tbody>
			            </table>
	          		</div> 
	      		</div>
      		<% end %>

			<% if @aprove.any? %>
	      		<div class="col-xl-6">
	      			<div class="table-stats order-table ov-h">
			            <table class="table table_form ">

			            	<thead>
			            		<tr>
			            			<th colspan="3"><span class="badge badge-warning"> Tienes <%= @aprove.count %> Documento Pendiente de Aprobar</span></th>
			            		</tr>
			            	</thead>
			              <thead>
			                <tr>
			                  <th class="serial">#</th>
			                  <th>Usuario</th>
			                  <th>Informacion</th>
			                </tr>
			              </thead>

			              <tbody>
			                <% @aprove.each_with_index do |aprove, position| %>
			                  <tr>
			                    <td class="serial"><%= position + 1 %>.</td>
			                    <td class="avatar">
			                      <div class="round-img">
			                        <%= aprove.user.avatar? ? image_tag(aprove.user.avatar_url(), class: "rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "rounded-circle")%>
			                        </div>
			                    </td>
			                    <td>
			                    	<div class="text-center">
			        					<a href="/documents/<%= aprove.id %>">
			         						<i class="fas fa-info-circle"></i>
			         					</a>
			                    	</div>
			                    </td>	
			                  </tr>
			                <% end %>
			              </tbody>
			            </table>
	          		</div> 
	      		</div>
      		<% end %>
      	</div>

       </div>
    </div>
</div>


<style type="text/css" media="screen">
	.padding{
		padding: 4px !important;
	}

	.fa-info-circle{
		font-size: 28px;
    	color: #ffc107;
    	cursor: pointer;
	}
</style>

app/views/home/user.html.erb
<div class="row">
  <div class="col-xl-8">

    <div class="card">
      <div class="card-body">
        <legend>Crear Nuevo Usuario</legend>

        <div class="col-md-12 no-padding">
          <hr>
        </div>

        <%= form_tag create_user_path, method: :post, remote: true, class: "needs-validation", :novalidate => true do %>
          <%# render "users/shared/error_messages", resource: resource %>

          <div class="row">
              <div class="col-md-4">
                  <%= label_tag "Primer Nombre" %><br />
                  <%= text_field_tag :first_name, nil, class: "form form-control", :placeholder => "Nombre", id: "validationCustom01", :required => true  %>
                <div class="invalid-feedback">
				    Requerido!
				</div> 
              </div>

              <div class="col-md-4">
                  <%= label_tag "Segundo Nombre" %><br />
                  <%= text_field_tag :second_name, nil, class: "form form-control", :placeholder => "Segundo Nombre" %>                
              </div>

              <div class="col-md-4">
                  <%= label_tag "Primer Apellido" %><br />
                  <%= text_field_tag :first_last_name, nil, class: "form form-control", :placeholder => "Primer Apellido" %>                
              </div>
          </div>

          <br>

          <div class="row">
              <div class="col-md-4">
                  <%= label_tag "Segundo Apellido" %><br />
                  <%= text_field_tag :second_last_name, nil, class: "form form-control", :placeholder => "Segundo Apellido" %>
              </div>

              <div class="col-md-4">
                  <%= label_tag "Tipo de Documento" %><br />
                  <%= select_tag 'document_type', options_for_select(select_documento),{:class => 'form form-control'}%>                 
              </div>

              <div class="col-md-4">
                  <%= label_tag "Numero de Documento" %><br />
                  <%= text_field_tag :document_number, nil, class: "form form-control", :placeholder => "Numero de Documento" %>                
              </div>
          </div>

          <br>

          <div class="row">

            <div class="col-md-6">
              <%= label_tag "Fecha de Cumpleaños" %><br />
              <%= date_field_tag :birthday, nil, class: "form form-control", :placeholder => "Fecha de Cumpleaños" %>  
            </div>

            <div class="col-md-6">
              <%= label_tag "Cargo" %><br>
              <%= select_tag 'position_id', options_for_select(get_cargo.collect{ |u| ["#{u.name}", u.id] },{}), {:multiple => false, class: 'form-control', include_blank: false, id: "validationCustom01", :required => true, :prompt => 'Selecciona una Opcion' }%>

                  <div class="invalid-feedback">
                      Requerido!
                  </div> 
            </div>	

            <div class="col-md-6">
              <%= label_tag :email %><br>
              <%= email_field_tag :email, nil, class: "form form-control", :placeholder => "Email", id: "validationCustom01", :required => true %>
                <div class="invalid-feedback">
				    Requerido!
				</div> 
            </div>

          </div>

          <br>

          <div class="col-md-12 no-padding">
            <hr>
          </div>

          <div class="row">
            <div class="col-md-6">
                <%= label_tag "Contraseña" %>
                <%= password_field_tag :password, nil, class: "form form-control", :placeholder => "Contraseña", id: "validationCustom01", :required => true %>
                <div class="invalid-feedback">
				    Requerido!
				</div> 
            </div>

            <div class="col-md-6">
                <%= label_tag "Confirmar Contraseña" %>
                <%= password_field_tag :password_confirmation, nil, class: "form form-control", :placeholder => "Confirmar Contraseña", id: "validationCustom01", :required => true %>
                <div class="invalid-feedback">
				    Requerido!
				</div> 
            </div>
          </div>

      </div>
    </div>


  </div>

    <div class="col-xl-4">

      <div class="card">
        <div class="card-body">

          <div class="col-md-12 text-center">
           <img  class="user-avatar rounded-circle" id="edit-avatar" src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg" alt="" />
             <br><br>
             <%= file_field_tag :avatar, class: "form form-control", id: "img1" %>
          </div>
          <br><br>
          <div class="col-md-12 modal-footer">
            <%= submit_tag "Guardar", class: "btn btn-warning" %>
            <%= link_to "Volver", users_path, class: "btn btn-light" %>
          </div>

        </div>
      </div>

    </div>

  <% end %>
</div>

<style type="text/css" media="screen">

  #edit-avatar{
    height: 117px;
  }

</style>