config/routes.rb
Rails.application.routes.draw do
  get 'document_comments/create'
  resources :procesos
  resources :documents
  resources :document_types
  resources :created_fields
  resources :fields
  resources :process_maps
  resources :proces
  resources :positions
  resources :diagnosticos

  post "document_comment", to: "document_comments#create",  as: "document_comment"
  get "comment_index", to: "document_comments#comment_index", as: "comment_index"

  root 'home#index'
  get "user/new", to: "home#user", as: "user"
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  post '/tinymce_assets', to: 'tinymce_assets#create'

  devise_scope :user do
    post "create_user", to: "users/registrations#create_user", as: "create_user" 
  end
  get "all_users", to: "home#create_user", as: "users"
  
  patch "document_update/:id/:number", to: "documents#update_docu", as: "document_update"
  
  post "version_document/:id", to: "documents#new_document", as: "nuevo_document"

  post "documents_ready/:id", to: "documents#ready", as: "documents_ready"
  get "pdf_docment/:id", to: "documents#documents_pdf", as: "pdf_document"
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id                 :bigint(8)        not null, primary key
#  header             :text
#  footer             :text
#  logo               :string
#  ubication_logo     :string
#  proces_id          :integer
#  coding_type        :string
#  coding             :string
#  document_type_id   :integer
#  user_id            :integer
#  user_create_id     :integer
#  user_review_id     :integer
#  user_aprove_id     :integer
#  create_date        :date
#  review_date        :date
#  aprove_date        :date
#  version            :integer
#  review             :integer
#  is_last            :boolean
#  state_review       :boolean          default(FALSE)
#  state_aprove       :boolean          default(FALSE)
#  finish_document    :boolean
#  document_state     :string
#  document_source    :string
#  coutn              :integer
#  document_file      :string
#  change_description :text
#  name               :string
#  proceso_id         :integer
#  is_copy            :boolean
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Document < ApplicationRecord

  
  before_create :create_code  


	include AASM
	belongs_to :document_type, optional: true
	belongs_to :user
  belongs_to :proceso
	belongs_to :user_aprove, :class_name => 'User', optional: true
	belongs_to :user_review, :class_name => 'User', optional: true
  has_many :created_fields

	aasm column: "document_state" do
    state :in_creation, initial: true
  	state :create
  	state :review
  	state :aprove
  	state :ready

    event :document_create do
      transitions form: [:in_creation], to: [:create]
    end 

  	event :document_review do
  		transitions from: [:create], to: [:review]
  	end

  	event :document_aprove do
  		transitions from: [:review], to: [:aprove]
  	end

  	event :rejected do
  		transitions from: [:review, :aprove], to: [:ready]
  	end

  end

  def create_code

    count = Document.where(document_type_id: self.document_type_id, proceso_id: proceso_id).maximum(:coutn)
    type_document_prefix = DocumentType.find(self.document_type_id).prefix
    proceso_prefix = Proceso.find(self.proceso_id).prefix


    self.coutn = count == 0  || count.blank? || count.nil?   ?  1 :  count + 1
   
    
    self.coding = type_document_prefix + "-" + proceso_prefix +"-" + self.coutn.to_s 
    
  end

end

app/models/document_type.rb
# == Schema Information
#
# Table name: document_types
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  file        :boolean
#  prefix      :string
#  responsible :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class DocumentType < ApplicationRecord
	has_and_belongs_to_many :field
	has_many :document
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy, :update_docu, :ready, :documents_pdf, :new_document]
  before_action :authenticate_user!
  include ApplicationHelper
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @comments = DocumentComment.where(document_id: @document.id)
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  def new_document
    nuevo = {
      user_id: @document.user.id,
      document_type_id: @document.document_type.id,
      user_review_id: @document.user_review.id,
      name: @document.name,
      version: @document.version + 1,
      coding: @document.coding,
      document_source: @document.document_source,
      user_aprove_id: @document.user_aprove.id,
      proceso_id: @document.proceso.id,
      header: @document.header,
      footer: @document.footer,
      is_last: true,
    }

    @document.update(is_last: false)
    @new = Document.create(nuevo)

    if @new.save
        redirect_to edit_document_path(@new.id)
    end

  end

  def documents_pdf
      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "formatos1",
          :template => 'documents/pdfs/document.pdf.erb',
          :layout => 'pdf.html.erb',
          :show_as_html => params[:debug].present?
      end
    end 
  end


  def ready
    @document.update(finish_document: true);
    SendEmailJob.set(wait: 30.seconds).perform_later(@document, 1)
    @document.document_create!
  end

  # GET /documents/1/edit
  def edit
    if get_finish_document(@document.state_aprove, @document.state_review) == true
        render file: "#{Rails.root}/public/404", :layout => false, :status => :not_found
      else

      unless @document.user.id == current_user.id  
        render file: "#{Rails.root}/public/404", :layout => false, :status => :not_found
      end
    end
  end

  # POST /documents
  # POST /documents.json
  def create
      @document = Document.new(document_params)

      respond_to do |format|
        if @document.save
          format.html { 
            if @document.document_source == "Existente"
              redirect_to documents_path
              else

              redirect_to edit_document_path(@document.id), notice: 'Document was successfully created.' 
            end
          }
          format.json { render :show, status: :created, location: @document }
        else
          format.html { render :new }
          format.json { render json: @document.errors, status: :unprocessable_entity }
        end
      end
    
  end

  #bundle exec rake jobs:work
  #heroku run bundle exec rake jobs:work

  def update_docu
    if params[:number].to_i == 1
        @document.update(aprove_date: Time.now, state_aprove: true)
        @document.document_aprove!
      else
        @document.update(review_date: Time.now, state_review: true)
        @document.document_review!
        SendEmailJob.set(wait: 30.seconds).perform_later(@document, 2)
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        @document.document_type.field.each do |field|  
          if CreatedField.where(document_id: @document.id, field_id: field.id).any?
            CreatedField.where(document_id: @document.id, field_id: field.id).last.update(content: params[:"#{field.name}"])

          else
            CreatedField.create(field_id: field.id , document_id: @document.id, content: params[:"#{field.name}"], user_id: current_user.id)
          end
        end
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit!
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <div class="card-body">
          <div class="col-md-3 no-padding-left">
              <h3>
                <% if action_name == "new" %>
                  Nuevo Documento
                  <% else %>
                  Editar Documento
                <% end -%>
              </h3>
          </div>
          <br>
                          <%= tinymce_assets %>
          <%= form_with(model: document, local: true, :html => {class: "needs-validation", :novalidate => true}) do |form| %>
            <% if document.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

                <ul>
                <% document.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="row">
            <% if !get_review.exists? %>

              <div class="col-md-12">
                <%= form.label "Nombre" %><br>
                 <%= form.text_field :name, class: "form form-control", id: "validationCustom01", :required => true %>
                  <div class="invalid-feedback">
                      Requerido!
                  </div>
                 <br>
              </div>
              <div class="col-md-4">
                <%= form.label "Procceso" %><br>
                <%= form.select 'proceso_id', get_procesos.map { |u| [u.name, u.id] }, {:prompt => 'Procceso'},{:class => 'form form-control', id: "validationCustom01", :required => true}%>
                <div class="invalid-feedback">
                    Requerido!
                </div>
              </div>

              <div class="col-md-4">
                <%= form.label "Tipo de Documento" %><br>
                  <%= form.select 'document_type_id', get_document_type.map { |u| [u.name, u.id] }, {:prompt => 'Tipo de Documento'},{:class => 'form form-control', id: "validationCustom01", :required => true}%>
                  <div class="invalid-feedback">
                      Requerido!
                  </div>
              </div>

              <div class="col-md-4">
                <%= form.label "Fecha de Creacion" %><br>
                  <%= form.date_field :create_date, class: "form form-control", id: "validationCustom01", :required => true %>
                  <div class="invalid-feedback">
                      Requerido!
                  </div>
              </div>
              <br><br><br><br> 
              <div class="col-md-4">
                <%= form.label "Revisa" %><br>
                <%= form.select 'user_review_id', get_user.map { |u| [u.first_name? ? u.first_name : u.email, u.id] }, {:prompt => 'Revisa'},{:class => 'form form-control', id: "validationCustom01", :required => true}%>
                <div class="invalid-feedback">
                    Requerido!
                </div>
              </div>

              <div class="col-md-4">
                <%= form.label "Aprueba" %><br>
                <%= form.select 'user_aprove_id', get_user.map { |u| [u.first_name? ? u.first_name : u.email, u.id] }, {:prompt => 'Aprueba'},{:class => 'form form-control', id: "validationCustom01", :required => true}%>
                <div class="invalid-feedback">
                    Requerido!
                </div>
              </div>


              <div class="col-md-4">
                <%= form.label "Version" %><br>
                  <% if action_name == "new" %>
            <%= form.number_field :version, :value => 1,class: "form form-control" %>
             <% else -%> 
             <%= form.number_field :version, :value => @document.version ,class: "form form-control" %>

             <% end -%>
              </div>





             
            </div>
            <br>
            <% if action_name == "new" %>
              <div class="row">

                <div class="col-md-4">
                  <%= form.label "Tipo de Creación" ,style: "display:inline-block"%>
                    <%= form.select 'document_source', options_for_select(select_document_source), {},{:class => 'form form-control document_source'}%>
                </div>

                <div class="col-md-4 form-import" style="display: none;">
                  <label>Importar</label>
                  <%= form.file_field :document_file, class: "form form-control"  %>
                </div>

              </div>
            <% end -%>
            <br>
            <% if action_name == "edit"  && @document.document_source != "Existente" %>
                  <% @document.document_type.field.order(id: :desc).each do |docu| %>
                    <div class="col-md-12 no-padding">
                      <label><%= docu.name %></label>
                      <% if docu.field_type == "Texto"%>
                        <% if CreatedField.where(document_id: @document.id, field_id: docu.id).any? %>
                          <% create = CreatedField.where(document_id: @document.id, field_id: docu.id).last %>
                          <textarea rows="4" name="<%= docu.name %>" cols="50" id="field<%= docu.id %>"><%= create.content %></textarea>
                          <% else %>
                          <textarea rows="4" name="<%= docu.name %>" cols="50" id="field<%= docu.id %>"></textarea>
                        <% end -%>
                      <% end -%>

                      <script type="text/javascript">
                        $('#field<%= docu.id %>').froalaEditor({
                            height: 200,
                            charCounterCount: false,
                            language: 'es',
                            placeholderText: '<%= docu.name %>'

                        })
                      </script>
                    </div>
                  <% end %>
                <br>
                <div class="col-md-12 no-padding">
                  <%= form.label :header %>
                  <%= form.text_area :header, class: "form form-control" %>
                </div>
                <br>

                <%= tinymce uploadimage: true %>
                <div class="col-md-6 no-padding">
                  <%= form.label "Cambiar Descripcion" %>
                  <%= form.text_area :change_description, :rows => 10, :cols => 130, class: "form form-control tinymce" %>

                </div>
                <%= tinymce %>
                <% elsif  @document.document_source == "Existente" %>
                <div class="row">
                    
                  <div class="col-md-4">
                    <%= form.label "Tipo de Creación" ,style: "display:inline-block"%>
                      <%= form.select 'document_source', options_for_select(select_document_source), {},{:class => 'form form-control document_source'}%>
                  </div>

                  <div class="col-md-4">
                      <label>Cargar Archivo</label>
                      <%= form.file_field :document_file, class: "form form-control"  %>
                  </div>

                  </div>
                  <br>
                <div class="col-md-6 no-padding">
                  <%= form.label "Cambiar Descripcion" %>
                  <%= form.text_area :change_description, class: "tinymce" %>
                </div>
              <% end -%>

              <% end %>
            <br>

            <% if action_name == "new" %>
                <%= form.hidden_field :user_id, :value => current_user.id %>
                <%= form.hidden_field :is_last, :value => true %>
            <% end -%>

            <div class="col-md-12 modal-footer">
              <%= form.submit "Siguiente", class: "btn btn-success", id: "btn-save" %>
              <%= link_to "Volver", documents_path, class: "btn btn-light" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>


  <style type="text/css" media="screen">
    .fr-toolbar{
          border-top: 5px solid #fbcf00 !important;
    }
    #check
    {
          display: inline-block;
    width: 30px;
    height: 30px;
    margin-left: 11px;
    position: relative;
    top: 10px;
    }
    .opacidad{
         opacity: 0.5;
        filter: alpha(opacity=50); /* For IE8 and earlier */
        cursor: default;
    }

  </style>

<script type="text/javascript">
jQuery(document).ready(function($) {

    $(".document_source").change(function() {
    var $input = $( this );

    if ($input.val() == "Existente"){
      console.log('true');
       $(".form-import").fadeIn("show");
    }else {
      $(".form-import").fadeOut("show");
      console.log('false');
    }

  });


    $(document).on('turbolinks:request-end', function() {
  if (tinyMCE) { tinyMCE.remove(); }
});

});



</script>

app/views/documents/edit.html.erb
<%= render 'form', document: @document %>

app/views/documents/index.html.erb
<div class="orders">
  <div class="row">
    <div class="col-xl-12">
      <div class="card">

        <div class="card-body">
          <h4 class="box-title">Documentos </h4>
        </div>

        <div class="card-body">
          <div class="table-stats order-table ov-h">
            <table class="table table_form ">

              <thead>
                <tr>
                  <th>Codigo</th>
                  <th>Versión</th>
                  <th>Nombre</th>
                  <th>Tipo</th>
                  <th>Procceso</th>
                  <th class="text-center">Estado Del Documento</th>
                                        <!--
                  <th class="text-center">Creado</th>
                  <th class="text-center">Estado de Revisado</th>
                  <th class="text-center">Estado de Aprobacion</th>
                  <th>Estado del Documento</th>
                                  -->
                  <th colspan="4">Acciones</th>
                </tr>
              </thead>

              <tbody>
                <% @documents.order(version: :desc).each do |document| %>
                  <tr>
                    <td><%= document.coding %></td>
                    <td><%= document.version %></td>
                     <td><%= document.name %></td>
                      <td><%= document.document_type.name if document.document_type %></td>
                      <td><%= document.proceso.name if document.proceso %></td>
                      <td class="text-center"><%= get_traslate(document.document_state) %></td>
                      <!--
                      <td class="text-center"><%= get_icon(document.finish_document).html_safe %></td>
                      <td class="text-center"><%= get_icon(document.state_review).html_safe %></td>
                      <td class="text-center"><%= get_icon(document.state_aprove).html_safe %></td>
                      <td class="text-center"><%= get_traslate(document.document_state) %></td>
                      -->
                      <td>
                        <%= link_to document, class: "btn", data: {toggle: "tooltip", placement: "bottom" }, title: "Ver Documento" do %>
                          <i class="fas fa-eye"></i>
                        <% end -%>

                        <% estado =  get_finish_document(document.state_aprove, document.state_review) %>

                        <% unless estado == true %>
                          <%= link_to edit_document_path(document), data: {toggle: "tooltip", placement: "bottom", turbolinks: false }, title: "Editar", class: "btn" do %>
                            <i class="fas fa-pencil-alt"></i>
                          <% end -%>
                        <% end -%>

                        <%= link_to pdf_document_path(document.id, :format => "pdf"), data: {toggle: "tooltip", placement: "bottom" }, title: "Generar Pdf", target:"_blank", class: "btn" do %>
                          <i class="fas fa-file-alt"></i>
                        <% end -%>

                        <a data-toggle="tooltip" data-placement="bottom" title="" class="btn" data-confirm="Estas Seguro?" rel="nofollow" data-method="post" href="/version_document/<%= document.id %>" data-original-title="Duplicar">
                          <i class="fas fa-copy"></i>
                        </a>

                        <a href="/documents/<%= document.id %>" class="btn" data-method="delete" data-toggle="tooltip" data-placement="top" title="Eliminar Documento" data-confirm="Estas Seguro?">
                          <i class="fas fa-trash-alt"></i>
                        </a>
                        
                      </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div> 
        </div>

        <div class="col-md-12 modal-footer">
          <%= link_to 'Nuevo Documento', new_document_path, class: "btn btn-success " %>
        </div>
   

      </div> 
    </div>  
  </div>
</div>


<style type="text/css" media="screen">
  .true{
    color: green;
  }

  .false{
    color: red;
  }

</style>

<script type="text/javascript">
jQuery(document).ready(function($) {
  $('[data-toggle="tooltip"]').tooltip()
});
</script>

app/views/documents/new.html.erb
<%= render 'form', document: @document %>

app/views/documents/ready.js.erb
toastr["success"]("EL Documento Se envio a " + '<b><%= @document.user_review.first_name %>' + " " +  '<%= @document.user_review.first_last_name %> </b>' + " para revisar");

app/views/documents/show.html.erb
<div class="col-xl-12">
  <div class="card">
    <div class="card-body">
      <!--
      <div class="col-md-4 float-right">
        <div class="row text-center">

          <div class="col-md-3 text-center">
            <small><b>Revisado</b></small>
            <i class="fas fa-check true"></i>
          </div>

          <div class="col-md-3 text-center no-padding-right">
            <small><b>Aprobado</b></small>
            <i class="fas fa-check true"></i>
          </div>

          <div class="col-md-3 text-center no-padding-right">
            <button class="btn btn-outline-success"><i class="fas fa-check true"></i></button>
          </div>

        </div>
      </div>
      -->

      <div class="col-md-12 text-right no-padding-right">
        <% if @document.user.id == current_user.id %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong"> Mensajes </button>

            <% if get_finish_document(@document.state_review, @document.state_aprove) == true %>
              <button type="button" class="btn btn-outline-success" disabled>Este Documento Fue Aprobado Por Todos</button>
            <% else %>
              <% if @document.finish_document == true %>
                <button type="button" class="btn btn-outline-success" disabled>Pendiente de Aprobación</button>
                <% else %>
                <%= link_to "¿Este Documento Esta Listo Para Revision?", documents_ready_path(@document.id), method: :post, remote: true, class: "btn btn-info " %>
              <% end -%>
            <% end -%>

        <% end %>
      </div>



      <% if @document.user_review.id == current_user.id %>
        <div class="col-md-12 text-right no-padding-left">
          <% if @document.state_review == true %>
            <button type="button" class="btn btn-outline-success" disabled>Revision Aprobada <%= @document.user_review.first_name %></button>
          <% else %>
            <%= link_to "¿Este Documento Esta Listo Para Revision?", document_update_path(@document.id, 2), class: "btn btn-info", method: :patch, remote: true %>
          <% end -%>
        </div>
      <% end -%>

      <% if @document.user_aprove.id == current_user.id %>
        <div class="col-md-12 text-right no-padding-left">
          <% if @document.state_aprove == true %>
            <button type="button" class="btn btn-outline-success" disabled>Aprobastes Este Documento <%= @document.user_aprove.first_name %></button>
          <% else %>
            <%= link_to "¿Este Documento Esta Listo Para Revision?", document_update_path(@document.id, 1), class: "btn btn-info", method: :patch, remote: true %>
          <% end -%>
        </div>
      <% end -%>

      <br>
      <div class="col-md-12 no-padding">
        <%== @document.header%>
      </div>
      <br><br>

      <% @document.created_fields.each do |field|%>

        <%== field.content%>

      <%end%>

      <%== @document.change_description%>

      <div class="modal fade bd-example-modal-lg" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Comentarios
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </h5>
            </div>
            <div class="modal-body">
              <% @comments.each do |comen| %>

                <div class="card">
                  <div class="card-body">
                    <div class="media">
                      <%= comen.user.avatar? ? image_tag(comen.user.avatar.avatar_url(), class: "align-self-center mr-3 rounded-circle height") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "align-self-center mr-3 rounded-circle height")%>
                      <div class="media-body">
                        <h4 class="mt-0"><%= comen.title %></h4>
                        <br>
                        <p><%= comen.description %></p>
                        <div class="col-md-4 float-right no-padding text-right">
                          <small class="text-muted"><%= comen.user.first_name? ? comen.user.first_name : comen.user.email %>  <%= comen.user.first_last_name? ? comen.user.first_last_name : comen.user.email %></small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              <% end -%>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
          </div>
        </div>
      </div>


      <%# unless @document.user.id == current_user.id %>
        <!--
        <%# form_tag document_comment_path, method: :post, remote: true do %>
          <%# text_field_tag :title, nil, class: "form form-control", :placeholder => "Titulo" %>
          <br>
          <%# text_area_tag :description, nil, class: "form form-control", :placeholder => "Descripcion", :rows => 6 %>
          <%# hidden_field_tag :document_id, nil, :value => @document.id %>

          <%# if @document.user_review.id == current_user.id %>
            <%# hidden_field_tag :user_id, nil, :value => @document.user_review.id %>
          <%# elsif @document.user_aprove.id == current_user.id %>
            <%# hidden_field_tag :user_id, nil, :value => @document.user_aprove.id %>
          <%# end -%>
          
        <%# end -%>
      -->

      <%# end -%>



      <table class="table" style="margin-top: 40px;">
        <thead class="text-center">
          <tr>
            <th>Creado por </th>
            <th>
              <% if @document.state_review == true %> 
                Revisado
                <% else %>
                Pendiente de Revisar
              <% end -%>
            </th>
            <th>
              <% if @document.state_aprove == true %> 
                Aprobado
                <% else %>
                Pendiente de Aprobar
              <% end -%>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-center">
              <strong><%= @document.user.first_name? ? @document.user.first_name : @document.user.email %>  <%= @document.user.first_last_name %></strong>
              <p><%= get_date(@document.create_date) %></p>
            </td>

            <td class="text-center">
              <strong><%= @document.user_review.first_name %>  <%= @document.user_review.first_last_name %></strong>
              <% if @document.state_review == true %>
                <p><%= get_date(@document.review_date) %></p>
              <% else %>
                <p>Pendiente de Revisar</p>
              <% end -%>
            </td>

            <td class="text-center">
              <strong><%= @document.user_aprove.first_name %>  <%= @document.user_aprove.first_last_name %></strong>
              <% if @document.state_aprove == true  %>
                <p><%= get_date(@document.aprove_date) %></p>
              <% else %>
                <p>Pendiente de Aprobacion</p>
              <% end -%>
            </td>

          </tr>
        </tbody>
      </table>

      <div class="col-md-12 no-padding">
        <%== @document.footer %>
      </div>

      <div class="col-md-12 modal-footer">
        <% unless @document.user.id == current_user.id %>
          <%= link_to "Comentar", comment_index_path(:commen => @document), class: "btn btn-warning", remote: true %>
        <% end -%>
          <%= link_to 'Volver', documents_path, class: "btn btn-success " %>
      </div>

    </div>
  </div>
</div>

<style type="text/css" media="screen">
  table{
        border: 1px solid #8a87877a;
  }

  table td{
       border: 1px solid #8a87877a;
  }

  td{
        padding: 10px;
  }

  .user{
        height: 148px;
  }

  .height{
    height: 110px;
  }
</style>

app/views/documents/update_docu.js.erb
<% if params[:number].to_i == 1 %>
	toastr["success"]('<b><%= @document.user_aprove.first_name? ? @document.user_aprove.first_name : @document.user_aprove.email %></b>' + 'La Confirmacion fue Enviada con <b> Exito!</b>');
<% else %>
	toastr["success"]('<b><%= @document.user_review.first_name? ? @document.user_review.first_name : @document.user_review.email %></b>' + 'La Confirmacion fue Enviada con <b> Exito!</b>');
<% end %>