config/routes.rb
Rails.application.routes.draw do
  get 'document_comments/create'
  resources :procesos
  resources :documents
  resources :document_types
  resources :created_fields
  resources :fields
  resources :process_maps
  resources :proces
  resources :positions
  resources :diagnosticos

  post "document_comment", to: "document_comments#create",  as: "document_comment"
  get "comment_index", to: "document_comments#comment_index", as: "comment_index"

  root 'home#index'
  get "user/new", to: "home#user", as: "user"
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  post '/tinymce_assets', to: 'tinymce_assets#create'

  devise_scope :user do
    post "create_user", to: "users/registrations#create_user", as: "create_user" 
  end
  get "all_users", to: "home#create_user", as: "users"
  
  patch "document_update/:id/:number", to: "documents#update_docu", as: "document_update"
  
  post "version_document/:id", to: "documents#new_document", as: "nuevo_document"

  post "documents_ready/:id", to: "documents#ready", as: "documents_ready"
  get "pdf_docment/:id", to: "documents#documents_pdf", as: "pdf_document"
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proceso.rb
# == Schema Information
#
# Table name: procesos
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  admin_user  :integer
#  user_id     :integer
#  proces_type :string
#  prefix      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Proceso < ApplicationRecord
	has_many :documents
	belongs_to :user
	has_many :positions
end

app/controllers/procesos_controller.rb
class ProcesosController < ApplicationController
  before_action :set_proceso, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /procesos
  # GET /procesos.json
  def index
    @procesos = Proceso.all
  end

  # GET /procesos/1
  # GET /procesos/1.json
  def show
  end

  # GET /procesos/new
  def new
    @proceso = Proceso.new
  end

  # GET /procesos/1/edit
  def edit
  end

  # POST /procesos
  # POST /procesos.json
  def create
    @proceso = Proceso.new(proceso_params)

    respond_to do |format|
      if @proceso.save
        format.html { redirect_to procesos_url, notice: 'Proceso was successfully created.' }
        format.json { render :show, status: :created, location: @proceso }
      else
        format.html { render :new }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procesos/1
  # PATCH/PUT /procesos/1.json
  def update
    respond_to do |format|
      if @proceso.update(proceso_params)
        format.html { redirect_to procesos_url, notice: 'Proceso was successfully updated.' }
        format.json { render :show, status: :ok, location: @proceso }
      else
        format.html { render :edit }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procesos/1
  # DELETE /procesos/1.json
  def destroy
    @proceso.destroy
    respond_to do |format|
      format.html { redirect_to procesos_url, notice: 'Proceso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proceso
      @proceso = Proceso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proceso_params
      params.require(:proceso).permit(:name, :description, :admin_user, :user_id, :proces_type, :prefix)
    end
end

app/helpers/procesos_helper.rb
module ProcesosHelper
end

app/views/procesos/_form.html.erb
<div class="modal fade" id="product-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <% if action_name == "new" %>
            Nuevo Proceso
            <% else %>
            Editar Proceso 
          <% end -%>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </h5>
      </div>
      <div class="modal-body">
        <%= form_for(proceso, remote: true) do |form| %>


        <div class="row">
          <div class="col-md-6">
            <%= form.label "Nombre" %>
            <%= form.text_field :name, class: "form form-control" %>
          </div>

          <div class="col-md-6">
            <%= form.label "Tipo de Procceso" %>
            <%= form.select 'proces_type', options_for_select(select_type_proces), {},{:class => 'form form-control'}%>
          </div>
                   <div class="col-md-6">
                    <br>
            <%= form.label "Prefijo" %>
            <%= form.text_field :prefix, class: "form form-control" %>
          </div>
        </div>




        <br>
        <div class="field">
          <%= form.label "Descripcion" %>
          <%= form.text_area :description, class: "form form-control", :rows => 6 %>
        </div>

        <br>
        <%= form.hidden_field :admin_user %>
        <%= form.hidden_field :user_id, :value => current_user.id %>

        <div class="col-md-12 modal-footer">
          <%= form.submit "Guardar", class: "btn btn-success" %>
        </div>
      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/procesos/edit.html.erb
<h1>Editing Proceso</h1>

<%= render 'form', proceso: @proceso %>

<%= link_to 'Show', @proceso %> |
<%= link_to 'Back', procesos_path %>

app/views/procesos/edit.js.erb
jQuery(document).ready(function($){
	$('<%= j render "form", proceso: @proceso %>').on('hidden.bs.modal', function (e) {
	$(this).remove();
	$('.modal-backdrop').remove();
	}).modal();

});

app/views/procesos/index.html.erb
<div class="orders">
  <div class="row">
    <div class="col-xl-12">
      <div class="card">

        <div class="card-body">
          <h4 class="box-title">Procesos </h4>
        </div>

        <div class="card-body">
          <div class="table-stats order-table ov-h">
            <table class="table table_form ">

              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Prefijo</th>
                  <th>Descripcion</th>
                  <th>Tipo de Processo</th>
                  <th>Acciones</th>
                </tr>
              </thead>

              <tbody>
                <% @procesos.each do |proce| %>
                  <tr>
                    <td><%= proce.name %></td>
                    <td><%= proce.prefix %></td>
                    <td><%= proce.description %></td>
                    <td><%= proce.proces_type %></td>

                    <td>
                       <%= link_to edit_proceso_path(proce), data: {toggle: "tooltip", placement: "bottom" }, remote: true, title: "Editar", class: "btn" do %>
                          <i class="fas fa-pencil-alt"></i>
                        <% end -%>

                        <a href="/procesos/<%= proce.id %>" class="btn" data-method="delete" data-toggle="tooltip" data-placement="right" title="Eliminar Documento" data-confirm="Estas Seguro?">
                          <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                  
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div> 
        </div>

        <div class="col-md-12 modal-footer">
          <%= link_to 'Nuevo Procceso', new_proceso_path, class: "btn btn-success ", remote:true %>
        </div>
   

      </div> 
    </div>  
  </div>
</div>

app/views/procesos/new.html.erb
<h1>New Proceso</h1>

<%= render 'form', proceso: @proceso %>

<%= link_to 'Back', procesos_path %>

app/views/procesos/new.js.erb
jQuery(document).ready(function($){
	$('<%= j render "form", proceso: @proceso %>').on('hidden.bs.modal', function (e) {
	$(this).remove();
	$('.modal-backdrop').remove();
	}).modal();

});

app/views/procesos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @proceso.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @proceso.description %>
</p>

<p>
  <strong>Admin user:</strong>
  <%= @proceso.admin_user %>
</p>

<p>
  <strong>User:</strong>
  <%= @proceso.user_id %>
</p>

<p>
  <strong>Proces type:</strong>
  <%= @proceso.proces_type %>
</p>

<p>
  <strong>Prefix:</strong>
  <%= @proceso.prefix %>
</p>

<%= link_to 'Edit', edit_proceso_path(@proceso) %> |
<%= link_to 'Back', procesos_path %>