config/routes.rb
Rails.application.routes.draw do
  get 'document_comments/create'
  resources :procesos
  resources :documents
  resources :document_types
  resources :created_fields
  resources :fields
  resources :process_maps
  resources :proces
  resources :positions
  resources :diagnosticos

  post "document_comment", to: "document_comments#create",  as: "document_comment"
  get "comment_index", to: "document_comments#comment_index", as: "comment_index"

  root 'home#index'
  get "user/new", to: "home#user", as: "user"
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  post '/tinymce_assets', to: 'tinymce_assets#create'

  devise_scope :user do
    post "create_user", to: "users/registrations#create_user", as: "create_user" 
  end
  get "all_users", to: "home#create_user", as: "users"
  
  patch "document_update/:id/:number", to: "documents#update_docu", as: "document_update"
  
  post "version_document/:id", to: "documents#new_document", as: "nuevo_document"

  post "documents_ready/:id", to: "documents#ready", as: "documents_ready"
  get "pdf_docment/:id", to: "documents#documents_pdf", as: "pdf_document"
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/field.rb
# == Schema Information
#
# Table name: fields
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  field_type :string
#  state      :boolean
#  required   :boolean
#  form       :string
#  admin_user :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Field < ApplicationRecord
	has_and_belongs_to_many :document_type
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.js
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.js
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name, :field_type, :state, :required, :form, :admin_user, :user_id)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<div class="modal fade" id="product-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <% if action_name == "new"%>
          Crear Nuevo Campo
          <% else %>
            Editar Campo
          <% end -%>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </h5>
      </div>
      <div class="modal-body">
        <%= form_with(model: field, remote:true) do |form| %>
        <% if field.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(field.errors.count, "error") %> prohibited this field from being saved:</h2>

            <ul>
            <% field.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="col-md-12 no-padding-left">
          <%= form.label "Nombre" %>
          <%= form.text_field :name, class: "form form-control" %>
        </div>

        <br>

        <%= form.hidden_field :field_type, :value => "Texto" %>


        <br>

        <div class="col-md-12 no-padding-left">
          <%# form.label "Agregar Al Formulario" %>
          <%# form.text_field :form, class: "form form-control" %>
        </div>

        <br>

        <!--
        <div class="row">
          <div class="col-md-6 text-center">
            <%# form.label "Estado" %>
            <%# form.check_box :state, class: "form form-control" %>
          </div>

          <div class="col-md-6 text-center">
            <%# form.label "Requerido" %>
            <%# form.check_box :required, class: "form form-control" %>
          </div>
        </div>
        -->
        
        <br>

        <%= form.hidden_field :admin_user %>
        <%= form.hidden_field :user_id, :value => current_user.id %>

        <div class="col-md-12 modal-footer">
          <%= form.submit "Guardar", class: "btn btn-success add_service" %>
        </div>

      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/fields/create.js.erb
jQuery(document).ready(function($){
$('#product-modal').modal('hide')
toastr["success"]("El Campo fue creado con <b> Exito!</b>");


            var markup = "<tr><td>" + "<%= @field.field_type %>" + "</td><td>" + "<%= @field.name %>" + "</td><td>" + '<%= link_to "Edit", edit_field_path(@field), remote:true %>' + '<%= link_to "Destroy", @field, method: :delete, data: { confirm: "Are you sure?" }, remote:true %>' + "</td>";
            $(".table_form tbody").append(markup);

        
        // Find and remove selected table rows
        //$(".delete-service").click(function(){
            //$(".table_services tbody").find('input[name="record"]').each(function(){
            	//if($(this).is(":checked")){
                    //$(this).parents("tr").remove();
                //}
            //});
        //});   
});

app/views/fields/destroy.js.erb
jQuery(document).ready(function($) {
	toastr["error"]("El Campo fue Eliminado con <b> Exito!</b>");
	$("#dele<%= @field.id %>").remove();
});	

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/edit.js.erb
jQuery(document).ready(function($){
	$('<%= j render "form", field: @field %>').on('hidden.bs.modal', function (e) {
	$(this).remove();
	$('.modal-backdrop').remove();
	}).modal();
});

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>


<div class="orders">
  <div class="row">
    <div class="col-xl-12">
      <div class="card">

        <div class="card-body">
          <h4 class="box-title">Campos Creados</h4>
        </div>

        <div class="card-body">
          <div class="table-stats order-table ov-h">
            <table class="table table_form ">

              <thead>
                <tr>
                  
                  <th>Nombre</th>
                  <th colspan="3">Acciones</th>
                </tr>
              </thead>

              <tbody>
                <% @fields.each do |field| %>
                  <tr id="dele<%= field.id%>">
                      <td><%= field.name %></td>
                      
                    <td>

                        <%= link_to edit_field_path(field), data: {toggle: "tooltip", placement: "bottom" }, remote:true, title: "Editar", class: "btn" do %>
                          <i class="fas fa-pencil-alt"></i>
                        <% end -%>

                        <a href="/fields/<%= field.id %>" class="btn" data-method="delete" data-toggle="tooltip" data-placement="bottom" title="Eliminar Tipo de Documento" data-confirm="Estas Seguro?">
                          <i class="fas fa-trash-alt" data-remote="true" ></i>
                        </a>

                    </td>
                    </tr>
                <% end %>
              </tbody>
            </table>
          </div> 
        </div>

        <div class="col-md-12 modal-footer">
          <%= link_to 'Nuevo Campo', new_field_path, class: "btn btn-success ", remote:true %>
        </div>

      </div> 
    </div>  
  </div>
</div>

<style type="text/css" media="screen">
  .true{
    color: green;
  }

  .false{
    color: red;
  }
</style>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Back', fields_path %>

app/views/fields/new.js.erb
jQuery(document).ready(function($){
	$('<%= j render "form", field: @field %>').on('hidden.bs.modal', function (e) {
	$(this).remove();
	$('.modal-backdrop').remove();
	}).modal();
});

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<p>
  <strong>Field type:</strong>
  <%= @field.field_type %>
</p>

<p>
  <strong>State:</strong>
  <%= @field.state %>
</p>

<p>
  <strong>Required:</strong>
  <%= @field.required %>
</p>

<p>
  <strong>Form:</strong>
  <%= @field.form %>
</p>

<p>
  <strong>Admin user:</strong>
  <%= @field.admin_user %>
</p>

<p>
  <strong>User:</strong>
  <%= @field.user_id %>
</p>

<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>

app/views/fields/update.js.erb
jQuery(document).ready(function($) {
	$('#product-modal').modal('hide')
	toastr["info"]("El Campo fue Actualizado con <b> Exito!</b>");
	var markup = "<tr><td>1</td><td>" +  "<%= @field.user_id %>"  + "</td><td>" + "<%= @field.field_type %>" + "</td><td>" + "<%= @field.name %>" + "</td><td>" + '<%= get_icon(@field.state).html_safe %>' + "</td><td>" + '<%= get_icon(@field.required).html_safe %>' + "</td><td>" + "<%= @field.form %>" + "</td><td>" + '<%= link_to "Edit", edit_field_path(@field), remote:true %>' + '<%= link_to "Destroy", @field, method: :delete, data: { confirm: "Are you sure?" }, remote:true %>' + "</td>";
    $(".table_form tbody").html(markup);
});